############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
    port: 7080

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: spring-cloud-config

eureka:
  server:
    hostname: localhost
    port: 7700
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/



