############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
    port: 7070

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: springCloud-zuul-server


zuul:
  routes:
    service-article:
      path: /service-article/**
      url: http://192.168.3.22:8004

  prefix: /api


