############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
  port: 8013

spring:
  redis:
    port: 6379
    database: 0
    password:
    host: 127.0.0.1




