############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
    port: 7070

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: springCloud-zuul-server

eureka:
  server:
    hostname: localhost
    port: 7700
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/

zuul:
  routes:
    service-article: /service-article/**
#      path: /service-article/**
#      service-id: service-article
#      url: http://192.168.3.22:8004

  prefix: /api


